server:
#配置端口号
  port: 8081
  servlet:
#项目访问前缀
    context-path:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dharma_mall?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
  data:
    mongodb:
      database: dharma
      port: 27017
      host: localhost